 CREATE TABLE movietbl (
    id VARCHAR2(10) PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    image_url VARCHAR2(500),
    genre VARCHAR2(50)
);



INSERT INTO movietbl (id, title, image_url, genre) VALUES ('m001', '반지의 제왕', 'https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg', 'SF');
INSERT INTO movietbl (id, title, image_url, genre) VALUES ('m002', '매트릭스', 'https://m.media-amazon.com/images/I/51EG732BV3L._AC_.jpg', 'SF');
INSERT INTO movietbl (id, title, image_url, genre) VALUES ('m003', '인터스텔라', 'https://m.media-amazon.com/images/I/A1JVqNMI7UL._AC_SY679_.jpg', 'SF');
INSERT INTO movietbl (id, title, image_url, genre) VALUES ('m004', '코코', 'https://i.namu.wiki/i/rqxqsW2qG1XsAyg6lwScYRd0MTiNqiHITUdP3RU-1z8oBZraG752Lm8esh2okyVklw_Z6xkz69H4jYysWDIomQ.webp', '	
Animation');

commit;

select * from movietbl;

select * from acorntbl;

select * from ncttbl;
drop table ncttbl;

create  table  ncttbl(
    name varchar2(30) , 
    birthday  varchar2(10)  
);





insert into ncttbl values( '황인준' , 0323) ;
insert into ncttbl values( '이민형' , 0802) ;
insert into ncttbl values( '이제노' , 0423) ;
insert into ncttbl values( '나재민' , 0813) ;
insert into ncttbl values( '종천러' , 1122) ;
insert into ncttbl values( '박지성' , 0205) ;
insert into ncttbl values( '이동혁' , 0606) ;
commit;


   CREATE TABLE reviewtbl (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR2(1000)
   );
   
 INSERT INTO reviewtbl (content) VALUES ('정말 만족스러운 제품이에요! 추천합니다.');
INSERT INTO reviewtbl (content) VALUES ('배송이 조금 느렸지만 제품은 좋아요.');
INSERT INTO reviewtbl (content) VALUES ('기대했던 것보다 별로였어요. 개선이 필요합니다.');

commit;
  