--p211 4~9문제
--4. EMP테이블을 사용하여 부서별로 직급별로 급여 합계 결과를 출력하세요
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (1000,10,'Tiger',3600);
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (2000,10,'Cat',3000);
COMMIT;

SELECT * FROM EMP;

--DEPTNO, ENAME, JOB, SAL

--이거는 뭐냐면 직급별 사원수를 구한거임
SELECT  DEPTNO,
        COUNT (DECODE(JOB,'CLERK','1')) CLERK,
        COUNT(DECODE(JOB,'MANAGER','1')) MANAGER,
        COUNT(DECODE(JOB,'PRESIDENT','1')) PRESIDENT,
        COUNT(DECODE(JOB,'ANALYST','1')) ANALYST,
        COUNT(DECODE(JOB,'SALESMAN','1')) SALESMAN
FROM EMP
GROUP BY DEPTNO;

--근데 이제 직급별 급여합계를 구하고 싶은거야 아 ㅇㅋ
--직급별 급여합계
SELECT  DEPTNO,
        SUM(SAL*(DECODE(JOB,'CLERK','1'))) CLERK,
        SUM(SAL*(DECODE(JOB,'MANAGER','1'))) MANAGER,
        SUM(SAL*(DECODE(JOB,'PRESIDENT','1'))) PRESIDENT,
        SUM(SAL*(DECODE(JOB,'ANALYST','1'))) ANALYST,
        SUM(SAL*(DECODE(JOB,'SALESMAN','1'))) SALESMAN
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

-- NULL값 0으로 출력
SELECT  DEPTNO,
        SUM(SAL*(DECODE(JOB,'CLERK','1'))) CLERK,
        SUM(SAL*(DECODE(JOB,'MANAGER','1'))) MANAGER,
        NVL(SUM(SAL*(DECODE(JOB,'PRESIDENT','1'))),0) PRESIDENT,
        NVL(SUM(SAL*(DECODE(JOB,'ANALYST','1'))),0) ANALYST,
        NVL(SUM(SAL*(DECODE(JOB,'SALESMAN','1'))),0) SALESMAN
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

--전체누적합 구하기
SELECT  DEPTNO,
        SUM(SAL*(DECODE(JOB,'CLERK',1))) CLERK,
        SUM(SAL*(DECODE(JOB,'MANAGER',1))) MANAGER,
        NVL(SUM(SAL*(DECODE(JOB,'PRESIDENT',1))),0) PRESIDENT,
        NVL(SUM(SAL*(DECODE(JOB,'ANALYST',1))),0) ANALYST,
        NVL(SUM(SAL*(DECODE(JOB,'SALESMAN',1))),0) SALESMAN
FROM EMP
GROUP BY ROLLUP(DEPTNO)
ORDER BY DEPTNO;


--최종답입니다용
SELECT  NVL(TO_CHAR(DEPTNO), ' ') DEPTNO,
        SUM(SAL*(DECODE(JOB,'CLERK',1))) CLERK,
        SUM(SAL*(DECODE(JOB,'MANAGER',1))) MANAGER,
        NVL(SUM(SAL*(DECODE(JOB,'PRESIDENT',1))),0) PRESIDENT,
        NVL(SUM(SAL*(DECODE(JOB,'ANALYST',1))),0) ANALYST,
        NVL(SUM(SAL*(DECODE(JOB,'SALESMAN',1))),0) SALESMAN,
        SUM(SAL) AS TOTAL
FROM EMP
GROUP BY ROLLUP(DEPTNO)
ORDER BY 6;

SELECT * FROM EMP;

--아 아니 이게 맞음.. 타이거랑 캣이 10번인데 직업이 없어서 10 토탈이 많은거였어.. 이런미친
SELECT  NVL(TO_CHAR(DEPTNO), ' ') DEPTNO,
        SUM(SAL*(DECODE(JOB,'CLERK',1))) CLERK,
        SUM(SAL*(DECODE(JOB,'MANAGER',1))) MANAGER,
        NVL(SUM(SAL*(DECODE(JOB,'PRESIDENT',1))),0) PRESIDENT,
        NVL(SUM(SAL*(DECODE(JOB,'ANALYST',1))),0) ANALYST,
        NVL(SUM(SAL*(DECODE(JOB,'SALESMAN',1))),0) SALESMAN,
        NVL(SUM(SAL*(DECODE(JOB,'',1))),0) "NULL", --NULL이라고 해서 안된거임 "NULL"해야됨
        SUM(SAL) AS TOTAL
FROM EMP
GROUP BY ROLLUP(DEPTNO)
ORDER BY 6;


--4. 예린
desc emp;
SELECT nvl (to_char (deptno), 'total'), 
       SUM(CASE WHEN job = 'CLERK' THEN sal ELSE 0 END) AS CLERK,
       SUM(CASE WHEN job = 'MANAGER' THEN sal ELSE 0 END) AS MANAGER,
       SUM(CASE WHEN job = 'PRESIDENT' THEN sal ELSE 0 END) AS PRESIDENT,
       SUM(CASE WHEN job = 'ANALYST' THEN sal ELSE 0 END) AS ANALYST,
       SUM(CASE WHEN job = 'SALESMAN' THEN sal ELSE 0 END) AS SALESMAN,
       SUM(sal) AS TOTAL
FROM emp
GROUP BY rollup (deptno) 
ORDER BY deptno;

--5. 정호
SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER(ORDER BY SAL) "TOTAL"
FROM EMP;

--6. 6번은 하지말라고햇덩

--7.

--8. 민환
select deptno, ename, sal, 
sum(sal) over( partition by  deptno order by sal) "total"
from emp;

--9. 유민
SELECT * FROM EMP;

SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER() AS TOTAL_SAL ,ROUND(SAL/SUM(SAL) OVER() * 100 , 2 ) AS "%"
FROM EMP;

SELECT DEPTNO, ENAME, SAL, SUM(SAL) OVER() AS TOTAL_SAL, ROUND(RATIO_TO_REPORT(SAL) OVER() * 100 , 2 ) AS "%"
FROM EMP;





