--4. EMP 테이블을 사용하여 부서별로 직급별로 급여 합계 결과를 출력하세요
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (1000,10,'Tiger',3600);
INSERT INTO EMP(EMPNO, DEPTNO, ENAME, SAL) VALUES (2000,10,'Cat',3000);
COMMIT;

SELECT * FROM EMP;


SELECT 